# Generated by Django 6.1.1 on 2026-09-15 08:08

"""
Update the Publisher model structure.

This migration removes the publisher creation date and website fields,
adds a many-to-many relationship between publishers and users, and
updates the publisher name field to be unique with a maximum length
of 200 characters.
"""

from typing import ClassVar

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Apply changes to the Publisher model."""

    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("news", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.RemoveField(
            model_name="publisher",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="website",
        ),
        migrations.AddField(
            model_name="publisher",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="publisher_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
