# Generated by Django 6.1.1 on 2026-09-15 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publisher",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="publisher",
            name="website",
        ),
        migrations.AddField(
            model_name="publisher",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="publisher_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
